version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  flask-server:
    image: local_container_flask:latest
    restart: always
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/